name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      # 🧠 Inject commit SHA + timestamp into index.html
      - name: Inject commit SHA and timestamp into HTML
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          DEPLOY_TIME=$(date -u +"%Y-%m-%d %H:%M UTC")
          sed -i "s|<!-- COMMIT_SHA -->|Commit: ${SHORT_SHA} — Deployed: ${DEPLOY_TIME}|" index.html

      # 🚀 Deploy to Azure Static Web App
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_WATER_035D99E1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "/"
